baseURL: "https://ospo.berkeley.edu/"
languageCode: "en-us"
title: "UC Berkeley's Open Source Program Office"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["taxonomy"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        enableDefault: true

params:
  author: "UC Berkeley Open Source Program Office"
  description: "UC Berkeley Open Source Program Office Website"
  font:
    name: "Open Sans"
    sizes: [400, 900]
  navbarlogo:
    image: dancing-logo.svg
    altText: Dancing OSPO logo
    text: Berkeley OSPO
    link: /
  navbar:
    - title: People
      url: /people
  footer:
    logo: dancing-logo.svg
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/berkeley-ospo/
        icon: github
