baseURL: "https://ospo.berkeley.edu/"
languageCode: "en-us"
title: "Berkeley Open Source Program Office"
theme: scientific-python-hugo-theme
relativeURLs: true
disableKinds: ["taxonomy"]

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    renderHooks:
      link:
        enableDefault: true

params:
  author:
    name: "Berkeley Open Source Program Office"
  description: "Berkeley Open Source Program Office Website"
  font:
    name: "Open Sans"
    sizes: [400, 900]
  navbarlogo:
    image: dancing-logo-berkeley.svg
    altText: Dancing OSPO logo
    text: Berkeley OSPO
    link: /
  navbar:
    - title: About
      url: /about
    - title: News
      url: /news
    - title: Projects
      url: /projects
  footer:
    logo: bids-banner-logo-white-cropped-left-for-website-footer.png
    socialmediatitle: ""
    socialmedia:
      - link: https://github.com/berkeley-ospo/
        icon: github
      - link: https://ucospo.net/tags/berkeley/atom.xml
        icon: rss-feed

    quicklinks:
      column1:
        title: ""
        links:
          - text: UC OSPO Network
            link: https://ucospo.net/
